import {
    BelongsToManyAddAssociationMixin,
    BelongsToManyCountAssociationsMixin,
    BelongsToManyGetAssociationsMixin,
    BelongsToManyHasAssociationMixin,
    BelongsToManyRemoveAssociationMixin,
    BelongsToManySetAssociationsMixin,
    CreationOptional,
    DataTypes,
    InferAttributes,
    InferCreationAttributes,
    Model,
    NonAttribute,
    Sequelize,
} from 'sequelize';
import {
    defaultIdColumnAttributes,
    defaultModelOptionsWithHooks,
} from '../../utils/models.utils';
import { Group } from '../models';

class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
    declare id: CreationOptional<string>;
    declare attrs: Record<string, unknown>;
    declare rules: string[];

    // association mixins generated by User.belongsToMany(User, { as: 'Connections' })
    declare addConnection: BelongsToManyAddAssociationMixin<User, string>;
    declare getConnections: BelongsToManyGetAssociationsMixin<User>;
    declare countConnections: BelongsToManyCountAssociationsMixin;
    declare hasConnection: BelongsToManyHasAssociationMixin<User, string>;
    declare removeConnection: BelongsToManyRemoveAssociationMixin<User, string>;
    declare setConnections: BelongsToManySetAssociationsMixin<User, string>;

    // association mixins generated by User.belongsToMany(Group)
    declare addGroup: BelongsToManyAddAssociationMixin<Group, string>;
    declare getGroups: BelongsToManyGetAssociationsMixin<Group>;
    declare countGroups: BelongsToManyCountAssociationsMixin;
    declare hasGroup: BelongsToManyHasAssociationMixin<Group, string>;
    declare removeGroup: BelongsToManyRemoveAssociationMixin<Group, string>;
    declare setGroups: BelongsToManySetAssociationsMixin<Group, string>;

    // eager-loading attributes
    declare Connections?: NonAttribute<User[]>;
    declare Groups?: NonAttribute<Group[]>;

    static initModel(sequelize: Sequelize): void {
        User.init(
            {
                id: defaultIdColumnAttributes(),
                // JSONB, not JSON, for `@>` containment support (same
                // reasoning as Resource.attrs).
                attrs: {
                    type: DataTypes.JSONB,
                    allowNull: false,
                    validate: {
                        maxSize(value: Record<string, unknown>) {
                            if (value === null) return;
                            const size = Buffer.byteLength(
                                JSON.stringify(value),
                                'utf8',
                            );
                            if (size > 64 * 1024) {
                                throw new Error('attrs exceeds 64KB limit');
                            }
                        },
                        hasUsername(value: Record<string, unknown>) {
                            if (value === null) return;
                            const username = value.username;
                            if (
                                typeof username !== 'string' ||
                                username.trim().length === 0
                            )
                                throw new Error(
                                    "attrs: 'username' is required and must " +
                                        'be a non-empty string',
                                );
                            if (username.trim().length < 2)
                                throw new Error(
                                    "attrs: 'username' must be at least 2 " +
                                        'characters',
                                );
                            if (username.trim().length > 128)
                                throw new Error(
                                    "attrs: 'username' must be at most 128 " +
                                        'characters',
                                );
                        },
                    },
                },
                rules: {
                    type: DataTypes.JSON,
                    allowNull: false,
                    validate: {
                        maxSize(value: string[]) {
                            if (value === null) return;
                            const size = Buffer.byteLength(
                                JSON.stringify(value),
                                'utf8',
                            );
                            if (size > 64 * 1024) {
                                throw new Error('rules exceeds 64KB limit');
                            }
                        },
                    },
                },
            },
            defaultModelOptionsWithHooks(sequelize),
        );
    }
}

export { User as _User };
